version: '2'
services:
 postgres:
  build: ./postgres
  environment:
    - POSTGRES_DB=dnarepairdb
    - POSTGRES_PASSWORD=docker
    - POSTGRES_USER=docker
  volumes:
    - ./dockerfiles/postgresql:/var/lib/postgresql
  network_mode: "service:nginx"

 django:
  build: .
  environment:
    - DJANGO_SETTINGS_MODULE=dnarepairdb.setting
    - STATIC_ROOT:/media/dnarepairdb/dnarepairdb_static
    - MEDIA_ROOT:/media/dnarepairdb/dnarepairdb_media
  #command: python manage.py runserver 0.0.0.0:8000
  #command: uwsgi --http :8001 --module ismirsnp.wsgi
  command: uwsgi --ini uwsgi.ini
  volumes:
   - ./dnarepairdb:/dnarepairdb
   - ./dockerfiles:/media/dnarepairdb
  network_mode: "service:nginx"

 nginx:
  build: ./nginx
  ports:
   - "447:443" # for nginx
   - "5437:5432" # for postgres
  volumes:
   - ./dockerfiles:/media/dnarepairdb
